### ISSUE TITLE
grpc exception

### ISSUE THREAD

**Issue by nazzour** [louiezzang/faiss-server#1]
Hello,
I am testing the faiss-server. I did follow all the install instructions. when I execute "python client_sample.py test --dim 200 --host localhost --port 50051" the test works well, however when I execute "python client_sample.py test --dim 512 --host localhost --port 50051" there is an exception:

"""
Traceback (most recent call last):
  File "client_sample.py", line 232, in <module>
    cli()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "client_sample.py", line 30, in test
    response = stub.Add(pb2.AddRequest(id=id, embedding=embedding))
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: "
        debug_error_string = "{"created":"@1638791670.309461779","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"Exception calling application: ","grpc_status":2}"
"""

Any idea ?
Thanks

**Comment by louiezzang** [comment]
Hi @nazzour ,

Can you start faiss-server again with this option(dimension size is 512 not 200)?
`$ ./run.sh nextmining/faiss-server:latest faiss-server 512 5 10 50051`
First of all, you need to start the server with the corresponding embedding dimension size which is 512 you want to use.
Please let me know if you have the same error again.

Thanks!

**Comment by nazzour** [comment]
Hi @louiezzang , I did launch with the correct dim and now it is working. I will test it and let you know the results. Thank you for your support
